### ISSUE TITLE
chore(cli): imajin-cli depends on imajin-ai via file: paths and cannot build in isolation

### ISSUE THREAD

**Issue by veteze** [ima-jin/imajin-ai#1568]
## Summary

`imajin-cli` cannot be typechecked, tested, or built on a machine that does not also have an `imajin-ai` checkout sitting next to it. Two dependencies point outside the repository, at a sibling clone of a different repo:

```json
"@imajin/vault-core": "file:../imajin-ai/packages/vault-core",
"@imajin/cid":        "file:../imajin-ai/packages/cid"
```

and `jest.config.cjs` hard-codes the same assumption:

```js
'^@imajin/vault-core$': '<rootDir>/../imajin-ai/packages/vault-core/src/index.ts'
```

Neither package is published — `npm view @imajin/vault-core` returns 404.

## Why this surfaced now

`imajin-cli` has never had a CI job that typechecks or builds, so nothing had ever tried. The typecheck workflow in ima-jin/imajin-cli#78 is the first, and it fails:

```
src/services/vault/VaultStore.ts(19,8): error TS2307:
  Cannot find module '@imajin/vault-core' or its corresponding type declarations.
```

plus three cascading `TS7006 implicit any` errors from the unresolved import.

This is the last blocker on #78, which is otherwise ready — the other 15 errors in that job were the `vault serve` splice and are fixed.

## Why it is worth fixing rather than working around

Beyond CI, this means:

- A fresh clone of `imajin-cli` does not build. Onboarding requires knowing to clone a second repo to a specific relative path.
- Local verification is quietly untrustworthy. `npm run type-check` passes on a developer machine and fails in CI, for reasons invisible from the CLI repo alone — a green local run proves nothing.
- The two repos are coupled by filesystem layout rather than by a version, so there is no way to say which `vault-core` the CLI is compatible with.

## Options

1. **Publish `@imajin/vault-core` and `@imajin/cid`, depend on versions.** Cleanest; `imajin-ai` already has `publish-packages.yml`. Introduces a real release step between the repos, which is arguably the point — the coupling becomes explicit and versioned.
2. **Check out `ima-jin/imajin-ai` alongside in CI.** Reproduces the local setup. Needs a cross-repo token, a `pnpm install` in the second checkout, and a `vault-core` build. Expect the `@noble/ed25519` ESM transform failure that `VaultStore.test.ts` already hits locally to appear once the module resolves — the `transformIgnorePatterns` entry does not match pnpm's nested `node_modules/.pnpm/...` layout.
3. **Vendor the consumed surface** into the CLI. Cheapest to land, worst to maintain; the whole point of `vault-core` is that both sides agree on the crypto.

Option 1 is the recommendation, with option 2 as a stopgap if #78 needs to land sooner.

## Acceptance

- `git clone imajin-cli && npm ci && npm run type-check && npm test` succeeds with no sibling checkout present.
- ima-jin/imajin-cli#78's `Typecheck & Test` passes.
- Once it does, add `Typecheck & Test` to the `imajin-cli` branch-protection ruleset (`20245960`), which today requires only `Analysis` precisely because this check cannot yet pass.

## Related

- ima-jin/imajin-cli#78 — the typecheck workflow, blocked on this
- #1547 — added typecheck gates; closed, but only the `imajin-ai` half actually shipped
- #1559 — the CI-gate audit that this came out of

**Comment by imajin-jin** [comment]
## Decision: Path A — publish the shared packages to npm (Ryan, 2026-08-02)

The two decisions "imajin-cli gets real CI" and "SonarCloud required" both dead-end here: imajin-cli can't build standalone, so it can't have real CI, so it can't be a required gate. We resolve it by making the shared deps real, resolvable npm packages rather than sibling `file:` paths.

**Scope — this is TWO packages, not one** (both `file:`-referenced + hardcoded in `jest.config.cjs`):
- `@imajin/vault-core` — currently `private: true`, 0 npm versions, but `main`/`types`/`exports`/`files` are already clean → structurally publish-ready.
- `@imajin/cid` — same treatment; confirm its package.json is publish-shaped too.

**Work:**
1. Flip `private: true` → publishable on both; decide **public vs. private npm scope** (`@imajin/*` org scope — Ryan to confirm registry/access, since vault-core is sovereign-credential core).
2. Add a `publishConfig` + a publish step (versioned; these are now real releases with a cadence).
3. Publish an initial version of each.
4. In imajin-cli: swap the two `file:../imajin-ai/packages/*` deps for the published `^x.y.z` versions, and remove the `<rootDir>/../imajin-ai/...` moduleNameMapper from `jest.config.cjs`.
5. Confirm imajin-cli#78 typecheck job goes green standalone.

**Then** (separate follow-ups): imajin-cli real CI (lint + typecheck + test + build, none swallowed), and add its checks to branch protection once green.

Note: publishing vault-core externally means its release process now carries the sovereign-credential core into a public/registry surface — worth a deliberate look at what's in `files: [dist/, src/]` before first publish (no keys, no fixtures with secrets).

**Comment by imajin-jin** [comment]
## Scope decision: PUBLIC npm (Ryan, 2026-08-02)

Both `@imajin/vault-core` and `@imajin/cid` publish as **public** packages. Rationale: the repo is public and every other Imajin package is public — private-scoping these would contradict the public-by-default thesis. Public source is the point; the only real risk is *secrets in the tarball*, not visibility.

**Pre-publish tarball check: PASSED.** Scanned the shippable tree (`files: [dist/, src/]`) of both packages for private keys / tokens / `.pem` / `.key` / `.env` / secret-bearing fixtures — none found. Safe to publish.

Supersedes the "public vs private" open question in the earlier Path-A comment. Remaining work is unchanged (flip `private:true`, add `publishConfig: {access:"public"}`, publish, swap imajin-cli `file:` deps → `^x.y.z`, drop the jest moduleNameMapper sibling path). Now Warp-ready.

**Comment by imajin-jin** [comment]
**Status 2026-08-03** — now tracked under epic #1573 (publish imajin-ai workspace packages to npm).

Progress toward unblocking this:
- #1569 (make `cid`/`vault-core` publishable) ✅ merged.
- #1572 (normalize the six publishable manifests → `0.8.0`) is **open** — the version-normalization prerequisite so the publish goes out with sane versions (they'd drifted across 4 version lines + a stray `1.0.0`).

Remaining to close this:
1. Merge #1572 → `0.8.0` on `main`.
2. Dispatch `publish-packages.yml`: `cid` → `vault-core` (dependency direction), dry-run then real.
3. Repoint `imajin-cli` at `@ima-jin/vault-core@^0.8.0`, drop the `pnpm.overrides` entry + the Jest `moduleNameMapper`, verify a clean clone builds/typechecks/tests with no sibling `imajin-ai` checkout → **closes this issue**.

**Comment by imajin-jin** [comment]
**Decision 2026-08-03 — option 4 (keep cid/vault-core ESM-only; fix the CLI test setup, not the packages).**

Investigated whether `cid`/`vault-core` should ship a CJS build (dual ESM+CJS) so the CLI's Jest can require them. They should **not**:

- `cid`'s runtime deps `multiformats` and `@ipld/dag-cbor` are **ESM-only** — their `exports` expose only `import` + `module-sync`, **no `require` condition**, and both are `type: module`. A CJS build of `cid` would emit `require("multiformats")` → **`ERR_REQUIRE_ESM` on Node 18/20** (only Node ≥22.12 can `require()` an ESM graph via `module-sync`). So a CJS half would ship a `require` entry that throws — a manifest that lies about what it supports.
- `vault-core`'s own deps (`@noble/*`) are require-safe, but it depends on `cid`, so it inherits the ESM-only constraint.
- Vendoring the ESM-only deps (`noExternal`) to force a working CJS build would hide them from `npm audit` — unacceptable on credential-adjacent packages.

**Therefore:** `cid` and `vault-core` stay **ESM-only** (`exports: { types, import }`) — an accurate manifest, not a workaround. The only consumer that can't handle ESM is the CLI's **Jest/ts-jest transform**, which is a property of the CLI's test setup. Fix on the CLI side with a `moduleNameMapper` line sitting next to the four existing entries already mapping `multiformats`/`@ipld/dag-cbor` for the identical reason. Real follow-up: migrate the CLI's Jest to ESM (it already has `type:module` + four ESM shims — heading there anyway).

**Do NOT add a CJS build to these two packages** — it reintroduces the throw. (Per epic #1573's honest-manifest build rule.)

Repoint step for this issue: CLI depends on `@ima-jin/vault-core@^0.8.0`, drop `pnpm.overrides` + Jest mapper for the sibling `file:` paths, add the ESM `moduleNameMapper` for the published packages, verify clean-clone build/typecheck/test with no sibling checkout.
